# Config file for cosmtrek/air

# Working directory
root = "."
tmp_dir = "tmp"

# Build options
[build]
  bin = "tmp/main" # Binary output path
  cmd = "go build -o tmp/main ." # Command to build the project
  include_ext = ["go", "tpl", "tmpl", "html"] # File extensions to watch
  exclude_dir = ["tmp", "vendor", "node_modules"] # Directories to exclude from watching
  exclude_file = ["air.toml"] # Files to exclude from watching
  follow_symlink = true # Follow symlinks

# Log options
[log]
  level = "debug" # Log level (debug, info, warn, error, fatal)
  color = true # Enable color in logs
  timestamp = true # Enable timestamp in logs

# Misc options
[misc]
  clean_on_exit = true # Clean up temporary files on exit

# Command to run after building
[run]
  cmd = "./tmp/main" # Command to run the built binary
  watch_delay = 200 # Delay in milliseconds before restarting after changes
  kill_signal = "SIGTERM" # Signal to kill the running process
  kill_timeout = 5 # Timeout in seconds to force kill the process